### ISSUE TITLE
Wiegand only reading from pins 21 and 20

### ISSUE THREAD

**Issue by knoend** [ugge75/Wiegand-Protocol-Library-for-Arduino-MEGA-2560#1]
When reading a tag, only pins 21 and 20 generate an output on serial.

**Comment by imberest** [comment]
Because the library is not finished. Pins 18 and 19 are commented. 2 and 3 should work. Also for pins 18 and 19 the code is missing

**Comment by ugge75** [comment]
bug fixed line 111, 112,113 & 114 uncommented
