### ISSUE TITLE
Reader C Doesn´t work

### ISSUE THREAD

**Issue by HugoTheBoss** [ugge75/Wiegand-Protocol-Library-for-Arduino-MEGA-2560#3]
I can´t get Reader C to work (18,19); Tested with different readers. A and B works perfect; Any Solution?

**Comment by Spoja** [comment]
His code is incomplete, I've pointed that out but it seems he isnt updating the library anymore. Anyways i have forked his library and "fixed" it to work with 3 readers.
You can find it here https://github.com/Spoja/Wiegand-Protocol-Library-for-Arduino-MEGA-2560/blob/master/WiegandMega2560.cpp

**Comment by HugoTheBoss** [comment]
Thx Spoja for your answer. I will try it the next days!

**Comment by yveshanoulle** [comment]
do I understand correctly that with this code, the verification of the cards, should happen inside the arduino code?

**Comment by ugge75** [comment]
all fixed in V2 , new V3 just released adding flexibility in pin assignment
