### ISSUE TITLE
Is it working with Pin Change Interrupts

### ISSUE THREAD

**Issue by ngohuunam** [ugge75/Wiegand-Protocol-Library-for-Arduino-MEGA-2560#4]
Hi

I have 4 wiegand and 1 mega 2560, there are 3 external interrupts in mega 2560. Does this library work with Pin Change Interrupts? anh How?

Thanks

**Comment by ngohuunam** [comment]
confirm work

**Comment by ugge75** [comment]
V3 just released ad compatible with all arduino board , if you need more reader attached to the same arduino  library can be extended .
